### ISSUE TITLE
Hur ge html-encodade strängar till namn åt 'tag'?

### ISSUE THREAD

**Issue by MalinAhlberg** [PerMalm/uneek#3]
Fråga till snabbis!!!

`tag('div', '&kulgrej;', ...)`
 
visas inte fint :(

**Comment by danr** [comment]
Hmm, varför skulle du vilja det? Du kan skriva unicode i strängarna.

Det vettigaste sättet verkar vara att använda `DOMParser` för att html-unescapa: https://stackoverflow.com/a/34064434

**Comment by MalinAhlberg** [comment]
Okdå. Tack hej.
