### ISSUE TITLE
Stora filer

### ISSUE THREAD

**Issue by PerMalm** [PerMalm/uneek#4]
Man far inte lagga mer an 5MB i localstorage. Stora filer gar alltsa inte att lasa in (speciellt ett problem nar man laser in xml).

Losningsforslag:

- Anvand backend vid stora filer
- Trixa for att lasa in xml bitvis (loser inte problemet helt, dock, men lite)
- Trixa for att fa anvanda mer minne

**Comment by danr** [comment]
Local storage används inte för att processera texterna. Det används bara för att textfälten ska komma ihåg sitt innehåll när webbläsaren stängts ner och startas igen. Så en annan lösning är att stänga av local storage-synkningen när så stora filer läses in.

**Comment by danr** [comment]
Fixat med https://github.com/PerMalm/uneek/commit/d6171f5a3fdf0dc35d8fac5d3125f7757d9f4122
