### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by PerMalm** [PerMalm/uneek#6]
När man kör xml:en nedan eller liknande så får man följande felmeddelande: 

TypeError: Assignment to constant variable. 

[xml_exempel.txt](https://github.com/PerMalm/uneek/files/1695030/xml_exempel.txt)

**Comment by danr** [comment]
Var får man felmeddelandet? I den röda textrutan under indatarutan?

**Comment by danr** [comment]
Här är filinnehållet:

```xml
<text>
<paragraph>
<sentence id="8f7-8c4">
<w pos="PN" msd="PN.UTR.SIN.DEF.SUB" lemma="|jag|" lex="|jag..pn.1|" sense="|jag..1:-1.000|" complemgram="|" compwf="|" ref="1" dephead="2" deprel="SS">Jag</w>
<w pos="VB" msd="VB.PRS.AKT" lemma="|vara|" lex="|vara..vb.1|" sense="|vara..1:-1.000|" complemgram="|" compwf="|" ref="2" deprel="ROOT">är</w>
<w pos="DT" msd="DT.UTR.SIN.IND" lemma="|en|" lex="|en..al.1|" sense="|den..1:-1.000|en..2:-1.000|" complemgram="|" compwf="|" ref="3" dephead="4" deprel="DT">en</w>
<w pos="NN" msd="NN.UTR.SIN.IND.NOM" lemma="|ost|" lex="|ost..nn.1|ost..nn.2|" sense="|ost..1:0.649|öster..2:0.351|" complemgram="|" compwf="|" ref="4" dephead="2" deprel="SP">ost</w>
<w pos="MAD" msd="MAD" lemma="|" lex="|" sense="|" complemgram="|" compwf="|" ref="5" dephead="2" deprel="IP">.</w>
</sentence>
</paragraph>
</text>
```

**Comment by PerMalm** [comment]
Yup! I den röda textrutan under indatarutan.

**Comment by danr** [comment]
Här är ett minimerat fall som failar:
```xml
<sentence>
<w a="A">.</w>
</sentence>
```

**Comment by danr** [comment]
Jag kan inte reproducera den här buggen när jag servar den själv på localhost med yarn, jag får den bara på din githubpages...

**Comment by PerMalm** [comment]
Ja, det verkar ha blivit något fel när vi lade upp det igår. Vet dock inte vad. Det fungerade först, men sedan körde jag en fil som var tyngre än gränsen för local storage; efter det kom felmeddelandet upp. Allt tycks dock funka fint med vanlig text.

**Comment by PerMalm** [comment]
Jag har kollat lite och det är just taggen``` <sentence>``` som väcker felmeddelandet. Om man byter ut det mot något annat så funkar det, typ:

```xml
<ost> 
<w a="A">.</w> 
</ost>
```

**Comment by MalinAhlberg** [comment]
Hm, då är det väl något med syntax-grejen som är fel. Kanske har jag skrivit fel på const/var där?

**Comment by MalinAhlberg** [comment]
Jag har triggat felet på nya versionen också. Men den är kanske byggd på gammal kod, så vi borde deploya den ännu nyare versionen och testa med den med.

**Comment by danr** [comment]
Vi borde göra try...catchen mindre bred så att den bara fångar felaktig XML och inte mer. Då får vi de andra felen i konsollen och kan debugga dem.
